version: '3'
services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/demodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd
      DEMO_APP_JWTCOOKIENAME: test
      DEMO_APP_JWTSECRET: testSecret # using the default value "testSecret" if the variable is not set
      DEMO_APP_JWTEXPIRATIONMS: 86400000
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=demodb
