spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/demodb
    username: root
    password: p@ssw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
demo:
  app:
    jwtCookieName: test
    jwtSecret: testSecret
    jwtExpirationMs: 86400000
