name: Spring Boot with MySQL

on:
  push:
    branches:
      - main

env: 
  MYSQL_VERSION: 5.7
  MYSQL_DATABASE: testdb
  MYSQL_USER: root
  MYSQL_PASSWORD: p@ssw0rd
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:${{ env.MYSQL_VERSION }}
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'

      - name: Build with Maven
        run: mvn clean install -DskipTests

        
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liyanamyc/server-user-mgt:latest
          build-args: DOCKER_USERNAME=${{ env.DOCKER_HUB_USERNAME }},DOCKER_PASSWORD=${{ env.DOCKER_HUB_PASSWORD }}
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/${{ env.MYSQL_DATABASE }}?useSSL=false&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: ${{ env.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.MYSQL_PASSWORD }}
