name: Push image

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      app:
        image: liyanamyc/server:tagname
        ports:
          - 8080:8080
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/myapp
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: p@ssw0rd

    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}
    
      - uses: actions/checkout@v2
      - name: Build and push Spring Boot Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/your-app-image-name:${{ github.sha }}
          build-args: DOCKER_USERNAME=${{ env.DOCKER_HUB_USERNAME }},DOCKER_PASSWORD=${{ env.DOCKER_HUB_PASSWORD }}
 
 
