name: Build and push Docker container

on:
  push:
    branches: [main]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  IMAGE_NAME: myserver
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME}}/${{ env.IMAGE_NAME}}:${{ github.sha }}
          builder: docker://docker.io/docker/dockerfile:1.2.1

      - name: Run MySQL database container
        uses: docker/compose-action@v1
        with:
          compose-file: docker-compose.yml
          service-name: mysqldb

      - name: Start application container
        run: |
          docker-compose up myapp

      - name: Stop containers
        run: |
          docker-compose down
