name: My GitAction Workflow

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: p@ssw0rd
          MYSQL_DATABASE: demodb
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
        
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
         java-version: '17.0.0'
          
    - name: Build with Maven
      run: mvn clean install -DskipTests

      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_ACCESS_TOKEN }}
      

    - name: Build and run container
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demodb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: p@ssw0rd
        DEMO_APP_JWTCOOKIENAME: test
        DEMO_APP_JWTSECRET: testSecret
        DEMO_APP_JWTEXPIRATIONMS: 86400000
      run: |
        docker build -t liyanamyc/myapp .
        docker run -d --name myapp-container -p 8080:8080 --env-file <(env | grep ^SPRING_) myapp
