name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: maven:3.8.4-jdk-17
    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: p@ssw0rd
          MYSQL_DATABASE: demodb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install -DskipTests        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}

      - name: Build Docker Image
        run: |
          docker build -t liyanamyc/myapp:latest \
            --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demodb \
            --build-arg SPRING_DATASOURCE_USERNAME=root \
            --build-arg SPRING_DATASOURCE_PASSWORD=p@ssw0rd \
            .
 
