name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  MYSQL_ROOT_PASSWORD: p@ssw0rd
  MYSQL_DATABASE: demodb
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests 
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.3-openjdk-17
      options: --network host
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: docker:20.10.7
      options: --network host
    env:
      DOCKER_USERNAME: ${{ env.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ env.DOCKER_ACCESS_TOKEN }}
    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build Docker Image
        run: |
          docker build --no-cache -t liyanamyc/myapp:latest \
              --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demodb \
              --build-arg SPRING_DATASOURCE_USERNAME=root \
              --build-arg SPRING_DATASOURCE_PASSWORD=p@ssw0rd \
              .
              
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liyanamyc/myapp:latest
