name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_HUB_USERNAME}/myapp:latest \
            --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demodb \
            --build-arg SPRING_DATASOURCE_USERNAME=root \
            --build-arg SPRING_DATASOURCE_PASSWORD=p@ssw0rd \
            --build-arg DEMO_APP_JWTCOOKIENAME=test \
            --build-arg DEMO_APP_JWTSECRET=testSecret \
            --build-arg DEMO_APP_JWTEXPIRATIONMS=86400000 \
            .

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_HUB_USERNAME}/myapp:latest
