name: Spring Boot with MySQL

on:
  push:
    branches:
      - main

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} 
  DOCKER_IMAGE_NAME: server-img
  MYSQL_DATABASE: myapp
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypass

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest .

      - name: Log in to Docker
        uses: docker/login-action@v1
        with: 
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Push Docker image
        run: |
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

      - name: Start MySQL service
        run: |
          docker run -d --name mysql \
            -e MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD \
            -e MYSQL_DATABASE=$MYSQL_DATABASE \
            -e MYSQL_USER=$MYSQL_USER \
            -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
            mysql:latest

      - name: Start Spring Boot application
        run: |
          docker run -d --name myapp-container \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/$MYSQL_DATABASE?useSSL=false&serverTimezone=UTC \
            -e SPRING_DATASOURCE_USERNAME=$MYSQL_USER \
            -e SPRING_DATASOURCE_PASSWORD=$MYSQL_PASSWORD \
            $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
