name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: openjdk:17
    services:
      mysqldb:
        image: mysql:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Compose
        run: |  
          docker build -t liyanamyc/myapp:latest \
            --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demodb \
            --build-arg SPRING_DATASOURCE_USERNAME=root \
            --build-arg SPRING_DATASOURCE_PASSWORD=p@ssw0rd \
            --build-arg DEMO_APP_JWTCOOKIENAME=test \
            --build-arg DEMO_APP_JWTSECRET=testSecret \
            --build-arg DEMO_APP_JWTEXPIRATIONMS=86400000 \
            .

      # Log in to Docker Hub
      - name: Push to dockerhub
        run: docker push liyanamyc/myapp:latest
