name: Docker Build image and Publish
on:
  push:
    branches:
      - main
      
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-16
    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: p@ssw0rd
          MYSQL_DATABASE: demodb

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
        
      - name: Build Docker Image
        run: |
          docker build --no-cache -t liyanamyc/myapp:latest \
            --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/demodb \
            --build-arg SPRING_DATASOURCE_USERNAME=root \
            --build-arg SPRING_DATASOURCE_PASSWORD=p@ssw0rd \
            .
        
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liyanamyc/myapp:latest
 
