name: Build and Push Spring Boot Container with MySQL

on:
  push:
    branches:
      - main
      

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 

      - name: Build MySQL container
        run: |
          docker build -t mysql:latest -f .

      - name: Start MySQL container
        run: |
          docker run --name mysql -d -e MYSQL_ROOT_PASSWORD=p@ssw0rd mysql:latest

      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liyanamyc/my-spring-boot-app:latest
          builder: docker/buildx-build
          build-args: |
            SPRING_PROFILES_ACTIVE=prod
            DB_HOST=mysql
            DB_PORT=3306
            DB_NAME=mydatabase
            DB_USERNAME=root
            DB_PASSWORD=p@ssw0rd
          cache-from: type=registry,ref=liyanamyc/my-spring-boot-app:cache
          cache-to: type=inline
