name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
      
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
        
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
         java-version: '17.0.0'
          
    - name: Build with Maven
      run: mvn clean install -DskipTests 
      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: liyanamyc/server-user-mgt:latest
          build-args: DOCKER_USERNAME=${{ env.DOCKER_HUB_USERNAME }},DOCKER_PASSWORD=${{ env.DOCKER_HUB_PASSWORD }}

    - name: Start MySQL container
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yml
        command: up -d mysql

    - name: Start Spring Boot container
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yml
        command: up -d spring-boot

    - name: Wait for containers to start
      run: sleep 30
 

    #- name: Stop containers
    #- uses: isbang/compose-action@v1.4.1
    #  with:
    #    compose-file: docker-compose.yml
    #    command: down
