name: Push Docker Compose Container
on:
  push:
    branches:
      - main

      
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}
          
      - name: Set up Docker Compose
        uses: docker/compose-cli@v0.7.7

      - name: Build and push Docker Compose container
        run: |
          export IMAGE_NAME=server
          docker-compose build && \
          docker tag $IMAGE_NAME liyanamyc/$IMAGE_NAME && \
          docker push liyanamyc/$IMAGE_NAME
        env:
          DOCKER_REGISTRY: docker.io
