name: Push Docker Compose

on:
  push:
    branches:
      - main
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker Compose
      uses: docker/compose-cli@v0.1.1
      with:
        login: true
        docker-compose-file: docker-compose.yml
        command: push
