name: User management workflow

on:
  push:
    branches:
      - main

env:
  MYSQL_DATABASE: testdb
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypass 
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  DOCKER_IMAGE_NAME: server-usr-mgt
  DOCKER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
         java-version: '17.0.0'

      - name: Build with Maven
        run: mvn package -DskipTests=true
        

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          -t ${{ env.DOCKER_HUB_USERNAME }}/ ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} \
          --build-arg JAR_FILE=target/*.jar \
          --build-arg MYSQL_DATABASE=${{ env.MYSQL_DATABASE }} \
          --build-arg MYSQL_USER= ${{ env.MYSQL_USER }} \
          --build-arg MYSQL_PASSWORD= ${{ env.MYSQL_PASSWORD }} \
          . 

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
 
