name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -t user-mgt-server:latest .
      - name: Push Docker Image
        run: docker push user-mgt-server:latest
