
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login and Build Docker image
        run: |        
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -t liyanakhrl/server -f ./Dockerfile .
      - name: Push Docker image
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-mgt-server
