name: Build and Publish Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_HUB_USERNAME: liyanamyc
  DOCKER_HUB_PASSWORD: Liyana21@@
  DOCKER_ACCESS_TOKEN: dckr_pat_q2rLEaHmEudyjUxCK8ZQPJLNPKY

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '18.0.1'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      
      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}
      
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
       username: ${{ env.DOCKER_HUB_USERNAME }}
       password: ${{ env.DOCKER_HUB_PASSWORD }}
       repository: ${{ env.DOCKER_HUB_USERNAME }}/springboot-server
       tags: ${{github.run_number}}
